config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root :to =>"homes#top"
  devise_for :users
  get "home/about"=>"homes#about"

  resources :books, only: [:index,:show,:edit,:create,:destroy,:update] do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end

  resources :users, only: [:index,:show,:edit,:update] do
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
  	get 'followers' => 'relationships#followers', as: 'followers'
    # # "あるユーザーがフォローしている人全員を表示させるためのルーティング"
    # get :followings, on: :member
    # # "あるユーザーをフォローしてくれている人全員（フォロワー一覧画面）をとってくるためのルーティング"
    # get :followers, on: :member
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get 'search' => 'searches#search'

end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  before_action :authenticate_user!


  def search
    @range = params[:range]
    @word = params[:word]

    if @range == "User"
      @users = User.looks(params[:search], params[:word])
    else
      @books = Book.looks(params[:search], params[:word])
    end
  end

end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/views/searches/_search.html.erb
<div class="search">
<% if user_signed_in? %>
  <div class="search_form">
    <%= form_with url:search_path, local: true, method: :get do |f| %>
      <%= f.text_field :word %>
      <%= f.select :range, options_for_select([['User'], ['Book']]) %>
      <%= f.select :search, options_for_select([["完全一致", "perfect_mach"], ["前方一致", "forward_match"], ["後方一致", "backword_match"], ["部分一致", "pertial_match"]]) %>
      <%= f.submit "検索", class: "btn btn-primary" %>
    <% end %>
  </div>
<% end %>
</div>

app/views/searches/search.html.erb
<table class="table table-hover table-inverse">
  <% if @range == "User" %>
  <h2>User search for"<%= @word %>"</h2>
   <thead>
     <tr>
     <th></th>
     <th>Name</th>
     </tr>
   </thead>
   <tbody>
     <% @users.each do |user| %>
      <tr>
        <td><%= image_tag user.get_profile_image, size:'100x100' %></td>
        <td><%= user.name %></td>
         <td><%= link_to 'Show', user_path(user), class: "user_#{user.id}" %></td>
      </tr>
    <% end %>
   </tbody>
  <% else %>
  <h2>Book search for"<%= @word %>"</h2>
   <thead>
     <tr>
     <th></th>
     <th>Title</th>
     <th>Opinion</th>
     </tr>
   </thead>
   <tbody>
    <% @books.each do |book| %>
      <tr>
       <td><%= link_to user_path(book.user) do %>
          <%= image_tag(book.user.get_profile_image, size:'50x50') %>
          <% end %>
        </td>
       <td><%= link_to book.title, book_path(book), class: "book_#{book.id}" %></td>
       <td><%= book.body %></td>
     </tr>
    <% end %>
   </tbody>
  <% end %>

</table>